### ISSUE TITLE
Create Gulpfile

### ISSUE THREAD

**Issue by Saborknight** [9i0xin9/framework-share#4]
So I'll create a gulpfile, any requests as to what it shall do?

Currently what I can implement is SASS compiling, autoprefixing, custom error handling, file watching (so that on save it compiles automatically), a build process in which the autoprefixing, compiling, minifying and concatenating will take place. 

Any further suggestions?

**Comment by 9i0xin9** [comment]
I think that for now all these features are enough, please taking care to set autoprefixing on all browser versions >0% I think that otherwise some old box features will not gonna compile properly.
Follow this folder structure or just set what do you think it's fitting better for this project.
Great support thanks

**Comment by Saborknight** [comment]
I might end up changing structure, I'll look at it properly tonight. 
I was looking into something to add to the gulpfile: https://www.npmjs.com/package/gulp-specificity-graph tell me what you think. It's based off the node version of the same.

**Comment by 9i0xin9** [comment]
Yesterday I've checked better https://github.com/keeganstreet/specificity and Ordering an array of selectors by specificity it's a good feature, but on the order it's not showing the weight of each one. Array items needs to be setted by hand (or add some js to extract automatically from a css file), so it's quite complicated to me use it in a fast proper way.
I can start to learn some js, but surely I'll need some time to achieve what I've mentioned.
About your link I have to figure out what will be the result of using it. It will compile the specificity of each style somewhere or what? Thanks for the explanation sometime I feel so cub here 😄

**Comment by Saborknight** [comment]
Nah, that's just because I gave you a link of the fork. Here's the original: https://github.com/pocketjoso/specificity-graph
It has more complete documentation. This one not only creates the graph, but also creates a json file with the relevant data  for everything

**Comment by Saborknight** [comment]
Added the general gulpfile. Will be adding the specificity graph to it soon.

**Comment by 9i0xin9** [comment]
Let's deep into the file, is it working on every commit or what?
I have to execute it from gulp command?

**Comment by Saborknight** [comment]
You execute it manually via the command line. Instructions will be released with the next changes to the gulpfile.

**Comment by Saborknight** [comment]
Instructions and bugfixes were implemented in the last gulpfile update. Still need to implement the specificity analyser.

**Comment by Saborknight** [comment]
Made another issue to directly address the addition of the specificity graph implementation to the gulpfile: #7 
Going to close this issue as the gulpfile is in a production ready state. If there are any more things to be added or changed in the gulpfile then create a new issue for each and assign me to it. I'll sort them out when I can.
